name: cpp-ethereum
version: master
summary: blockchain app platform
description: Ethereum C++ project

grade: devel
confinement: devmode

apps:
  eth:
    command: eth
  ethkey:
    command: ethkey
  ethvm:
    command: ethvm
  rlp:
    command: rlp

parts:
  cpp-ethereum:
    source: ../..
    plugin: cmake
    build-packages:
      - build-essential
      - libboost-all-dev
      - libgmp-dev
      - libleveldb-dev
      - libmicrohttpd-dev
      - libminiupnpc-dev
