name: aleth
version: master
summary: blockchain app platform
description: Ethereum C++ project

grade: devel
confinement: devmode

apps:
  eth:
    command: eth
  ethvm:
    command: ethvm

parts:
  aleth:
    source: .
    source-type: git
    plugin: cmake
    build-packages:
      - build-essential
      - libgmp-dev
