function(eth_apply TARGET REQUIRED)
	find_package(Eth)
	include_directories(SYSTEM ${Boost_INCLUDE_DIRS})
	include_directories(${CPPETHEREUM_BUILD})
	target_link_libraries(${TARGET} ${Boost_THREAD_LIBRARIES})
	target_link_libraries(${TARGET} ${Boost_RANDOM_LIBRARIES})
	target_link_libraries(${TARGET} ${Boost_FILESYSTEM_LIBRARIES})
	target_link_libraries(${TARGET} ${Boost_SYSTEM_LIBRARIES})
	target_link_libraries(${TARGET} ${LEVELDB_LIBRARIES})	#TODO: use the correct database library according to cpp-ethereum
	target_link_libraries(${TARGET} ${CRYPTOPP_LIBRARIES})
	target_link_libraries(${TARGET} ${ETH_CORE_LIBRARIES})
	if (UNIX)
		target_link_libraries(${EXECUTABLE} pthread)
	endif()

	eth_copy_dlls(${TARGET} ${EVMJIT_DLLS})
	eth_copy_dlls(${TARGET} ${OpenCL_DLLS})
endfunction()
