function(eth_apply TARGET REQUIRED)	
	if (READLINE_FOUND)
		target_include_directories(${TARGET} SYSTEM PUBLIC ${READLINE_INCLUDE_DIRS})
		target_link_libraries(${TARGET} ${READLINE_LIBRARIES})
		target_compile_definitions(${TARGET} PUBLIC ETH_READLINE)
	elseif (NOT ${REQUIRED} STREQUAL "OPTIONAL")
		message(FATAL_ERROR "Readline library not found")
	endif()
endfunction()
