# CMake generated Testfile for 
# Source directory: /Users/alex/dev/cpp-ethereum
# Build directory: /Users/alex/dev/cpp-ethereum/xcodebuild
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(alltests "/Users/alex/dev/cpp-ethereum/xcodebuild/test/Debug/testeth")
  set_tests_properties(alltests PROPERTIES  WORKING_DIRECTORY "/Users/alex/dev/cpp-ethereum/xcodebuild/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(alltests "/Users/alex/dev/cpp-ethereum/xcodebuild/test/Release/testeth")
  set_tests_properties(alltests PROPERTIES  WORKING_DIRECTORY "/Users/alex/dev/cpp-ethereum/xcodebuild/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(alltests "/Users/alex/dev/cpp-ethereum/xcodebuild/test/MinSizeRel/testeth")
  set_tests_properties(alltests PROPERTIES  WORKING_DIRECTORY "/Users/alex/dev/cpp-ethereum/xcodebuild/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(alltests "/Users/alex/dev/cpp-ethereum/xcodebuild/test/RelWithDebInfo/testeth")
  set_tests_properties(alltests PROPERTIES  WORKING_DIRECTORY "/Users/alex/dev/cpp-ethereum/xcodebuild/test")
else()
  add_test(alltests NOT_AVAILABLE)
endif()
subdirs(libdevcore)
subdirs(libevmcore)
subdirs(liblll)
subdirs(libserpent)
subdirs(sc)
subdirs(libsolidity)
subdirs(lllc)
subdirs(solc)
subdirs(libweb3jsonrpc)
subdirs(secp256k1)
subdirs(libp2p)
subdirs(libdevcrypto)
subdirs(libwhisper)
subdirs(libethcore)
subdirs(libevm)
subdirs(libethereum)
subdirs(libwebthree)
subdirs(test)
subdirs(eth)
subdirs(neth)
subdirs(libnatspec)
subdirs(libjsqrc)
subdirs(alethzero)
subdirs(third)
subdirs(mix)
