function(eth_apply TARGET REQUIRED)
	find_package (SSH2)
	eth_show_dependency(SSH2 ssh2)

	if (SSH2_FOUND)
		target_include_directories(${TARGET} SYSTEM PUBLIC ${SSH2_INCLUDE_DIRS})
		target_link_libraries(${TARGET} ${SSH2_LIBRARIES})
	elseif (NOT ${REQUIRED} STREQUAL "OPTIONAL")
		message(FATAL_ERROR "ssh2 library not found")
	endif()
endfunction()
