function(eth_apply TARGET REQUIRED)
	find_package (ZLIB)
	eth_show_dependency(ZLIB Zlib)
	if (ZLIB_FOUND)
		target_include_directories(${TARGET} SYSTEM PUBLIC ${ZLIB_INCLUDE_DIRS})
		# target_link_libraries(${TARGET} ${ZLIB_LIBRARIES})
		target_link_libraries(${TARGET} z)
	elseif (NOT ${REQUIRED} STREQUAL "OPTIONAL")
		message(FATAL_ERROR "Zlib library not found")
	endif()
endfunction()
